### ISSUE TITLE
Feature Request: Extend Layer Function

### ISSUE THREAD

**Issue by foreveryone1** [valentine195/obsidian-leaflet-plugin#125]
On some occasions I'd like to have the map remain visible and have layers appear over the map.

For example, when I indicate regions / borders in a fantasy map I'd like to have the base map visible, so I can use an 'overlay layer' with the same resolution as the base map to superimpose national borders.

**Comment by Moonbase59** [comment]
I agree, it might be nice to be able to add some "highlight" PNGs while Layer 0 stays visible. Otherwise you always have to re-duplicate the whole map:

**Comment by valentine195** [comment]
Feature added in 3.19.0, please see [this section of the ReadMe](https://github.com/valentine195/obsidian-leaflet-plugin#image-overlays).

**Comment by Moonbase59** [comment]
Will test these tomorrow, requires some test images to be prepared.

**Comment by Moonbase59** [comment]
Did some testing.

What I like:

- Keeping markers etc. in the same layer, i.e. only really _overlaying_ some parts, so that markers etc. stay intact. (As opposed to several "real" layers (like in caves) where you’d want to use separate markers.)
- Possibility to either specify or not specify coordinates (for full-image vs. partial-image PNG overlays).
- Real great: Possibility to switch on/off one or more layers. So one can show "where the action is" or maybe routes Frodo travelled …

What confuses me:

- Yet "another" coordinate system (top left/bottom right). Other mapping stuff usually works in Southwest/Northeast bounding boxes. Then again, it’s the same system (0,0 = top left) programs like Photoshop or GIMP use, so measuring for partial overlays is probably easier.
- What "coordinates" are these?
  - Pixels?
  - Percents?
  - Pseudo map coordinates relying on scale and/or bounds?
  - Do they use [x,y] or [y,x] notation?
- If specifying something smaller/larger than the overlay image, will it shrink/enlarge the overlay image?

I can imagine several use cases for overlay images, which _all_ require an understandable coordinate system:

- Overlaying "highlighted" parts of the map (i.e. show a dimmed map with a highlighted "action" or "play" area. This might be easiest using pixel coordinates (since the original map is also in pixels, and the overlays probably created using an image editing program).
- Overlaying "things" or monsters on a map (battery vending machine in the Colossal Caves, image of a dragon’s lair, etc.). This would possibly need "gaming map coordinates".
- Overlaying a logo, watermark, or map legend. This could use either pixel, percent, or "gaming" coordinates.

**Conclusion:** There is a need for a _common_, _understandable_ coordinate reference system, even for image maps. Which should work well with coordinates shown on the map, have a _common reference point_, _coordinate notation_ (lat,lon or y,x), and _sequence_ for bounding boxes.

My thoughts:

- _Pixels_ can/should only be used for _input_, if ever. They are only relevant in calculating the gaming coordinates in the first place (from the image dimensions), and possibly for the exact placement of transparent overlay images.
- _Percentages_ might come in helpful for placement of logos, watermarks and map legends, but are otherwise not too useful. Then again, these might be parsed easily (using an appended `%` sign).
- _Gaming map coordinates_ (as calculated using bounds and scale) seem to be the most useful for all-round use, i.e. markers, distance calculation on the map, giving coordinates to other players. They …
  - can be used inside the map (markers, distances, show & copy locations)
  - can be used _outside_ the map (i.e., in supporting notes, YAML, communicating with other players)
  - _should_ be used for establishing the initial map view (I think; instead of %lat/lon)
  - _could_ be used for placement of thing/monster images on the map
  - _could_ be used to place overlay images, like routes or terrain areas (albeit not as easy as pixels, _but_ one could directly pick up points from the map!)
  - _can_ be used with GeoJSON (in reversed notation)
  - _should_ always use the same sequence (i.e., [lat,lon] or [y,x]; except reversed in GeoJSON)
  - _should_ always use a defined sequence when specifying bounding boxes (bounds, areas, overlays). I strongly prefer "Southwest, Northeast" notation here, since it’s usual in other maps (real-world, too)
  - _must_ use the same reference (i.e., "where is 0,0?"). I somehow prefer 0,0 to be in the lower left ("Southwest") for mapping. It’s more natural for users (imagine a cartesian coordinate system), and—if using bounds—we already _have_ 0,0 in the lower left corner.
- The only drawbacks I can see if using "game map coordinates" in each and every place are …
  - One _has_ to do some initial `bounds` calculation. But in order to play a good game, players will surely use the same map for reference, and prefer "real" (gaming) coordinates.
  - Calculating the placement of terrain/route overlays is more difficult if just cutting/pasting parts of a map using an image editor. But I think since we gain the advantage of picking point coordinates directly from the map and being able to copy-paste these, i.e. for placement of things, monsters, logos, watermarks, map legends, it might be an averall gain. Also, the memory penalty of using a fullsize transparent PNG with just a small area filled in isn’t too much. (In case of highlighting parts of the terrain.)

Novel time again … think I should put this in "Discussions", for better visibility, hm?

**Comment by scarfur** [comment]
> Possible improvements:
> 
> It’d be nice if the
> 
> currently selected layer, and the
> currently selected overlays
> could be saved in the map instance. Thus, re-opening the map note would re-enable the last selected layer and/or the last selected overlays. If people use logo/watermark/thing/monster overlays, this might be beneficial.

Hope there is any chance this will come true like it did with tile layers :D
I would love to see permanent Image Overlays!
