### ISSUE TITLE
Getting current geo coordinates (GPS) on mobile Obsidian installs

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#176]
Since mobile devices can have access to GPS, and thus "live" coordinates (latitude, longitude in WGS 84) and elevation data (height in meters), I just opened a [feature request in the Obsidian forums](https://forum.obsidian.md/t/mobile-can-obsidian-api-provide-current-geo-location-gps-on-android-ios/21638).

Please support that, maybe add your ideas to it.

**It would be a _real cool feature_ having live Obsidian Leaflet maps!**

**Comment by valentine195** [comment]
Yeah, I would love this - see my reply in the forum post.

Maybe I'll send a message to the devs and ask about getting geolocation support. It could happen on Desktop too, just need the Google API key to have geolocation turned on (costs money - see [here](https://developers.google.com/maps/documentation/geolocation/usage-and-billing)).

**Comment by valentine195** [comment]
Doesn't look like this will be able to happen. Spoke with the Obsidian dev today and he said:

1. They don't want to enable location on mobile because it can look suspicious as to why a markdown text editor requires location permissions.
2. Because Google charges per-use for the geolocation services, probably won't happen on desktop either.

If either of these situations change, though, I'll definitely push an update to use it.

**Comment by Moonbase59** [comment]
Hm, too bad. `navigator.geolocation()` seems to be present, even on the desktop (but doesn’t return useful info)

**Comment by valentine195** [comment]
Yeah - the Google API key stored in the Electron process has to have it enabled. If it is not, it returns a 404.

**Comment by Moonbase59** [comment]
https://discord.com/channels/686053708261228577/840286264964022302/870728691544625202

**Comment by javiavid** [comment]
I've read on discord and it seems complicated to get ... 😢
Is there an easy way to do this on android with a macro app?
