### ISSUE TITLE
Problem loading GeoJson

### ISSUE THREAD

**Issue by ljantzen** [valentine195/obsidian-leaflet-plugin#202]
I have an issue loading a geojson file I created using https://geojson.io.  

I do not get any error messages, apart from a Notice saying `There was an error adding GeoJSON to map leaflet-map`.

My snippet is 

```
leaflet
id: leaflet-map
height: 500px
lat: 60.4675
long: 10
height: 500px
minZoom: 1
maxZoom: 20
defaultZoom: 8
unit: meters
scale: 1
marker: default, 60.4675, 5.302, [[Note]]
darkMode: false
geojson: [[Ferie2020geo.json]]
```

The files
[Ferie2020geo.json.txt](https://github.com/valentine195/obsidian-leaflet-plugin/files/6968471/Ferie2020geo.json.txt)
and 
 [Ferie 2021.md](https://github.com/valentine195/obsidian-leaflet-plugin/files/6968445/Ferie.2021.md)  are attached. 

It may be relevant that the geojson file is located in the same directory as the md file. And that the path from the vault root down to the file location contains spaces.  

I am running Obsidian on Ubuntu Linux.

**Comment by Moonbase59** [comment]
Just curious: What was the error? The empty `marker-symbol` in the GeoJSON?

@ljantzen Some remarks:

- In the GeoJSON, you can use the marker symbol names you have defined in _Obsidian Leaflet_ settings. `marker-color` and `marker-size` are currently ignored.
- You default view does neither include Bergen (the marker defined in the codeblock) nor the ferie location. (I had to zomm 2 steps out.)
- You might want to name your GeoJSON files using the `.geojson` extension. This makes it clearer, and some programs (and GitHub) actually recognise that extension.

Otherwise, your files work fine here (Obsidian 0.12.12/AppImage on Linux Mint 20.2). Without any changes, they show my default marker (gray) here:

![Ferie 2021 md () - Knowledgebase--Obsidian 0 12 12_122](https://user-images.githubusercontent.com/3706922/129049686-6ee7c0f5-3f1f-40b5-bcc3-acb17791c9f9.png)

**Comment by valentine195** [comment]
> Just curious: What was the error? The empty marker-symbol in the GeoJSON?

When a new marker feature is created, I build the tooltip display based on the `title` and `description` properties. I wasn't checking that the tooltip display had _actually_ been built, though, so when importing a file with markers that do not have those properties, it tried to access the display HTML and threw the error.
