### ISSUE TITLE
can not drag the image to another side

### ISSUE THREAD

**Issue by gh16683170** [valentine195/obsidian-leaflet-plugin#21]
Sometime the window is covered by another tab window, it would be nice if we can drag the image to any position we need to show the whole image. The gif shows that if i open the window side by side, the image will be left aligned, i hope we can make the image become left/right align by drag.
![can_not_drag3](https://user-images.githubusercontent.com/16650849/112140867-8a712100-8c0f-11eb-8b3a-730abeb51066.gif)

**Comment by valentine195** [comment]
Okay, I think this is happening because of the way the image maps are rendered. Basically, when the note loads, I tell Leaflet that the "bounds" of the map are exactly as big as the image (which is why you can't drag it side to side). But, if the element is resized, the bounds are not being updated.

I think this is fixable.

**Comment by valentine195** [comment]
This should be fixed in 1.1.0. Map containers will resize themselves as the window is resized. (80b6491)
