### ISSUE TITLE
Add ability to measure distance between points

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#25]
- [x] Marker tooltips are now fully interactable and display lat/lng
- [x] <kbd>Shift</kbd>/<kbd>Alt</kbd>-click on map to display coordinates of marker/mouse cursor location
- [x] <kbd>Shift</kbd>/<kbd>Alt</kbd>-click again to display _distance from original shift/alt click_ 
- [x] Add Arrow from original <kbd>Shift</kbd>/<kbd>Alt</kbd>-click to current mouse cursor location
     - [x] Display real-time distance on arrow
- [ ] Add control box to select units?  - Currently possible with `unit:` and `scale:` map parameters

**Comment by Moonbase59** [comment]
Please make it better than Google Maps do: I think that Ctrl-clicking _on a marker_ should use _that marker’s location_ instead of the mouse location.

Unfortunately, currently Ctrl-clicking on a marker opens the linked file in edit mode in a new pane.

**Comment by valentine195** [comment]
You'd rather have it start a distance calculation than open in a new window?

Would this work: using <kbd>Alt</kbd> (assuming I can fix #39) to measure distance instead of <kbd>Ctrl</kbd>. Ties in nicely to displaying the coordinates of the marker, too.

**Comment by Moonbase59** [comment]
Yeah, maybe you’re right. Might not pay to change Obsidian-like behaviour (`Ctrl`-clicking on an internal link in preview mode opens the linked file in edit mode).

But mainly I was referring to using the marker’s location if on one, instead of the mouse location. I think we all expect clicking on a _marker_ will use whatever it has to offer, not some per-chance mouse location (which is of course fine if we’re _not_ hovering over a marker).

**Comment by valentine195** [comment]
> Yeah, maybe you’re right. Might not pay to change Obsidian-like behaviour (`Ctrl`-clicking on an internal link in preview mode opens the linked file in edit mode).
> 
> But mainly I was referring to using the marker’s location if on one, instead of the mouse location. I think we all expect clicking on a _marker_ will use whatever it has to offer, not some per-chance mouse location (which is of course fine if we’re _not_ hovering over a marker).

Yeah, I think I like the idea of switching to <kbd>Alt</kbd> instead of <kbd>Ctrl</kbd> for distance.

This will natively use the marker's lat/long object if clicked on, not where the mouse is located.

> N.B.: How do you make the nice keyboard symbols? `<kbd>…</kbd>`?

Yep!

**Comment by Moonbase59** [comment]
Would Shift-clicking (when on a marker) also then use the _marker’s location_ instead of the mouse location for distance calculation? That’d be good.

But wait! There are some difficulties still:
- Ctrl-clicking a marker opens its linked file in a new pane in edit mode
- Ctrl-clicking _outside_ is for distance. This feels a little odd.
- Ah ok, these will go when Shift-clicking instead.

Don’t wait ;-)

**Comment by valentine195** [comment]
3.5.0 added

- Changes <kbd>Ctrl</kbd> to <kbd>Shift</kbd> or <kbd>Alt</kbd> for distance calculation
- allows using a marker for distance calculations - this uses the markers actual location, not mouse location

**Comment by Moonbase59** [comment]
Testing …

**Comment by Moonbase59** [comment]
**Brilliant!** When Shift-clicking on one marker, it displays coordinates, when Shift-clicking on the next one, it displays coordinates PLUS calculates distance. But that’s okay for me.

What I found:
- It appears that the location text popup _stays_ until you do something else. Good!
- It’s not possible to easily _copy_ the location displayed. Ideas?
- Could Shift-Click also show the location when _not_ on a marker? (And it possibly being copied?) So one could _find_ a location on the map and just _copypaste_ the location into a YAML header? :grin:

**Comment by valentine195** [comment]
> It’s not possible to easily copy the location displayed. Ideas?

Hmm, the easiest solution would be to just put it in the clipboard directly as soon as you shift-click, but that could be annoying.

> Could Shift-Click also show the location when not on a marker? (And it possibly being copied?) So one could find a location on the map and just copypaste the location into a YAML header? 😁

Yes, definitely possible. It would be the same tooltip functionality, so if I make it copy-able in one instance it will be globally (including the link display).

**Comment by Moonbase59** [comment]
Added a few ideas to the list ;-)

**Comment by Moonbase59** [comment]
Real fun working with you—fasted dev cycles ever. That makes testing a pleasure. And I see a real good working with maps in Obsidian now, thinking how "simple" it was at the beginning. Super usable and fun to work with! Thanks ever so much.

**Comment by Moonbase59** [comment]
> Yes, that should also be possible, although if I add the line, I'll probably _also_ display the distance on the line in real-time.

Wa-hoo! That’d be _real_ useful, because:
- you could move around with the mouse, possibly even zoom, while having the distance in eyesight and checking it ("I don’t wanna drive more than 100 km").
- you’d know where you started and where you’re going.
- it’d work on arbitrary map locations as well as on _exact_ marker coordinates.

Talking about use cases!

**Comment by valentine195** [comment]
### 3.6.0

- Marker tooltips are now fully interactable (copy/paste, click)
- Added ability to shift/alt click on map to display coordinates
- Added setting toggle to copy location to clipboard on shift/alt click

**Comment by Moonbase59** [comment]
No it doesn’t. Uninstalled/reinstalled. Only the `manifest.json` appears in the plugin folder, nothing else. Something broken?

**Comment by valentine195** [comment]
Hmm... I updated fine on my other computer.

Odd. Not sure what happened there.

**Comment by Moonbase59** [comment]
All works great so far, except when shift-clicking around the number of messages gets overwhelming. Still clipboard-copy and distance work fine!

Just in case  you want a distance with units—here is what I came up with for Dataview use, feel free to adapt! (This is actually a working example for `dataviewjs`. It should show about 416km, or the equivalent in other units.)

```javascript
function getDistance(origin, destination, unit='m') {
    // return distance in selected unit (m,km,yd,mi)

    var factor = 1.0;
    switch (unit) {
      case 'm':
        factor = 1.0;
        break;
      case 'km':
        factor = 1000.0;
        break;
      case 'yd':
        factor = 0.9144;
        break;
      case 'mi':
        factor = 1609.344;
        break;
      default:
        factor = 1.0;
        console.warn("getDistance: Invalid unit '%s', using 'm'. Valid units are: m,km,yd,mi.",unit);
    }

    var lon1 = toRadian(origin[1]),
        lat1 = toRadian(origin[0]),
        lon2 = toRadian(destination[1]),
        lat2 = toRadian(destination[0]);

    var deltaLat = lat2 - lat1;
    var deltaLon = lon2 - lon1;

    var a = Math.pow(Math.sin(deltaLat/2), 2) + Math.cos(lat1) * Math.cos(lat2) * Math.pow(Math.sin(deltaLon/2), 2);
    var c = 2 * Math.asin(Math.sqrt(a));
    var EARTH_RADIUS = 6371000; // 6,371 km in metres
    return c * EARTH_RADIUS / factor;
}
function toRadian(degree) {
    return degree*Math.PI/180;
}
// Below example should result in 416093.4 metres
dv.paragraph(getDistance([48.23875,10.37595], [51.7599915, 8.404249]).toLocaleString(undefined, {maximumFractionDigits: 1}) + " km Luftlinie");
```

**Comment by Moonbase59** [comment]
>     * Add control box to select units?  - Currently possible with `unit:` and `scale:` map parameters

I would scrap the old "units" code block stuff and use this for the recognized units (m, km, yd, mi in my case) then feed that to a wrapped `distance()` function that handles units.

So

```leaflet
id: Friends
markerFolder: People/Friends & Family
markerFolder: +Inbox
height: 500px
lat: 51.133333
long: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5
unit: km
```
would actually _use_ and _display_ kilometres. ;-)

**Comment by valentine195** [comment]
That makes sense for "real" maps - will still need a "scale" for image maps.

**Comment by Moonbase59** [comment]
Yep, you’d use a linear CRS + scaling then anyway, so maybe the wrapper function should support an extra "unit", or you use a separate distance calculator (linear is easy anyway).

**Comment by Moonbase59** [comment]
Is it intentional that a simple left-click on the map (_not_ on a marker) also displays and copies the coordinates? Looks like a good feature, getting the coords without calculating distances all the time …

**Comment by valentine195** [comment]
It should do it on shift/alt click on the map, not a basic left click - if it is doing it without modifiers it's actually a bug.

**Comment by valentine195** [comment]
> Btw, is there a means to get at Obsidian’s currently set locale? I’d much prefer the numbers to be displayed in the locale Obsidian is set to, rather than the system locale.

Hmm, I would think navigator.language would return the locale Obsidian is set to. Not sure how that works behind the scenes in Chromium.

**Comment by Moonbase59** [comment]
There must be something else, maybe from the Obsidian API … `navigator.language` returns `de` here even if my Obsidian is set to English. So it reflects the system locale, grmbl …

**Comment by valentine195** [comment]
Great! Didn't think to use moment - I tend to forget it exists because I don't like it much.

**Comment by Moonbase59** [comment]
Even more ideas … you oughta stop me …

Since I’ve just implemented a `getPredictedDrivingDistance()` for my Dataview calculations, you _could_ invent a setting "show straight-line or (predicted) driving distance", plus a setting field for the "prediction factor".

[Statistical research](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3835347/) for the U.S. has shown **1.417** a quite reliable value, with a relatively low standard deviation. For Germany, I found **1.3** a more realistic value, but this is only based on a small dataset, comparing with Google Maps’ "best route".

I simply use
```javascript
function getPredictedDrivingDistance(origin, destination, unit='m') {
    // The U.S. predict 1.417, based on statistical analysis.
    // For Germany, I’ve found 1.3 a good value (comparing w/ Google Maps "best route")
    var factor = 1.3;
    return getDistance(origin, destination, unit) * factor;
}
```

and get quite good results:

> 416,1 km Luftlinie, 540,9 km Fahrstrecke (geschätzt)
> 320,2 km Luftlinie, 416,2 km Fahrstrecke (geschätzt)
> 35,4 km Luftlinie, 46 km Fahrstrecke (geschätzt)

For real maps, this might turn out _useful_, since the straight-line distance is quite an artificial value (not all my friends are helicopter pilots). And if it was switchable, either in the settings or—maybe better—in the code block per map, one could have best of both worlds—again.

Since I’m usually looking at "what is nearby?" when visiting friends or places of interest, I’d of course be interested in the (estimated) _driving_ distance.

Talk about use cases! :grinning: Hope I don’t stress you too much with all my ideas!

**Comment by Moonbase59** [comment]
Hey, nice so far!
Maybe the  number of decimals shown for distances could be reduced? I usually only show 1 or 2.

Here is how a typical distance check goes (me, old fart, not the best eyesight anymore):
- First, move around, find, and try to exactly click the two points, avoiding all the preview popups you enabled because it’s otherwise nice to have them. (Kudos here for catching exact marker locations, and the line display!)
- Then, find the notification on the screen. Oh, it’s far away from my Obsidian window, somewhere at the top right corner of the screen.
- Then, on small screens, try to decipher whether the separator is a `,` or `.`.
- Then, possibly not remembering the language Obsidian is currently set to, think about if "818,953" has an _English thousands separator_ and means 818953 something, or if it has a _German decimal point_` and means 818.953.
- And all that before **poof!** the notification vanishes after 4 seconds or so.

Real life, as it goes. ;-)

That’s why I suggested having the distance display _within_ the map area somewhere (reduced eye movement), and probably display decimals not just in threes, to avoid confusing them with thousands.

**Comment by valentine195** [comment]
## 3.8.2

- Improved code structure
- #25 - removed requirement to shift-click to start distance drawing
- #25 - removed Notice of distance calculation
- #25 - added control box in bottom-left corner that displays previously measured distance
     - hovering the control box displays the previous distance line
     - clicking the control box pans the map to fit the line
- #25 - reduced number of decimals for distance display to 1
- #25 - moved distance line tooltip to mouse cursor position
- #25 - distance line tooltip is now always on top (no longer bounces around)


## 3.8.3
- Re-added shift-click requirement to distance line (otherwise markers would open the note, oops)

**Comment by Moonbase59** [comment]
Testing using 3.9.0:

What I like:
- Distance result inside map window
- Distance result persistent (until next measurement)
- Hover over it → show start/end points and line
- Click on it → apparently zoom in to distance

Bugs:
- Hovering over distance results sometimes only shows 1 point
- Clicking on it is not consistent:
  - sometimes shows zoomed in view of start/end point + line
  - sometimes shows entirely different set of points (measured some time ago) but with the distance shown for the latest measurement
  - sometimes zooms in (to a house number level) and shows one of the measured points, usually the first

**Comment by valentine195** [comment]
Please let me know if 3.9.2 fixes the issues you were seeing.

Also, please note that I added a requirement to <kbd>Ctrl</kbd> + <kbd>Shift</kbd> / <kbd>Alt</kbd> - click to copy coordinates to reduce Notice spam.

**Comment by Moonbase59** [comment]
Tested using 0.3.5: Another one well done! Purrrfect. (Yeah ok, cat lover, I admit.)

**Comment by Moonbase59** [comment]
Now one more thing to brainstorm about:

Copying the locations to clipboard results in an "array notation". Which is fine if you want to put it into YAML frontmatter oder code, but starts getting on my nerves when pasting into online maps or some other apps (because these won’t recognise the square brackets and you need to jump around with the cursor to remove them).

How do you feel about this?

I’d probably go for _not_ copying the brackets, so you could paste "just" lat, lon into anything. Agreed, if building YAML frontmatter you would have to type `[`, `]`, `cursor left` first. Or just use a template that create an "empty" `location: []` entry.

I’m just trying to convince the author of the _[Text Snippets plugin](https://github.com/ArianaKhit/text-snippets-obsidian)_ to [add a cursor positioning feature](https://github.com/ArianaKhit/text-snippets-obsidian/issues/3) so one could have a shortcut like `loc : location: [<|>]` which would insert the statement, then place the cursor in between the brackets. This might make it even easier, maybe you’d like to support this FR.

**Comment by valentine195** [comment]
Will be in the next release.

**Comment by Moonbase59** [comment]
Love the new features in 3.10.1 (Show all markers, reset view, filter markers).
Makes it so much more usable, I think.

**Comment by valentine195** [comment]
Wrong issue in commit - ignore.

**Comment by Moonbase59** [comment]
> Am I right or could "Show all markers" be zoomed in a little?

Fixed wonderfully in 3.12.1!

**Comment by Moonbase59** [comment]
**Usability:** When measuring a distance (especially when on an overlay),
- the mouse pointer,
- the metering tooltip, and
- the blue line

are all shown together in one place, making it impossibe to see a pointing arrow (if there is one), or at least the exact location where to click for the second point.

![Schreiben - Obsidian v0 12 3_060](https://user-images.githubusercontent.com/3706922/119721786-d50b5580-be6b-11eb-8490-3d5ddfd7df9a.png)

I’m a little lost here, I must say. The tooltip distance might be changed, but the mouse hand seems to overlap with the end of the line. And you don’t want to zoom _every time_.

Thoughts?

**Comment by valentine195** [comment]
Can you describe what you mean by zoom? Is the map zooming?

**Comment by Moonbase59** [comment]
No, I just meant "zoom in yourself until you are sure to hit the right spot" :-)
