### ISSUE TITLE
Map demonstrates strange functionality when the same document is viewed in edit and preview mode.

### ISSUE THREAD

**Issue by Cobalium** [valentine195/obsidian-leaflet-plugin#251]
Some examples of how it was experienced:

- Typing text causes an error for every character typed that does not result in a valid codeblock. (Typing "height: 100px would show an error on h... he... hei... until it was correct syntax.)
- Using the "Add marker to codeblock" feature does not show up in the codeblock until the document is reloaded and afterwards does not show up on the map until the codeblock is edited.

**Comment by valentine195** [comment]
Hey, I know this is years out of date :)

1. Obsidian re-renders notes in reading view every time you update the note content, but I could probably be less spammy with the notification.
2. Because of the above, the map waits until you close the file to write the marker to the code block, to avoid getting rerendered.
