### ISSUE TITLE
Bulk editor marker window from fullscreen

### ISSUE THREAD

**Issue by eltosti** [valentine195/obsidian-leaflet-plugin#45]
hey, found a weird bug, if you make a map fullscreen and then click twice to open the bulk editor marker, then exit fullscreen you can close the first screen of the editor, but no the second one.This blocks the application completely.

**Comment by Moonbase59** [comment]
Same here. 3.9.0 + Obsidian 0.12.3.

**Comment by Moonbase59** [comment]
**Wait …** To be honest, I’m unsure if I restarted Obsidian after the latest update of yours. I certainly did after [#45 happened](https://github.com/valentine195/obsidian-leaflet-plugin/issues/45), and now it seems to work.

For all 3 cases, is it supposed to play "modal", i.e., dim out the whole Obsidian surface area?

**Comment by valentine195** [comment]
Correct, it just uses Obsidian's modal constructor.

**Comment by Moonbase59** [comment]
Sorry I answered to the wrong issue … this was meant to go to #46 .

So to make it clear:
- #46 odd background – apparently my fault
- #45 fullscreen bulkedit problem – still there

**Comment by valentine195** [comment]
> hey, found a weird bug, if you make a map fullscreen and then click twice to open the bulk editor marker, then exit fullscreen you can close the first screen of the editor, but no the second one.This blocks the application completely.

Okay, I believe this is two separate issues:

1. When in full screen, the bulk edit modal is _behind_ the full screen map due to z-indexing.
2. Because the modal is behind the map instance, you can click the bulk edit button unlimited times, opening more and more modals.

To be clear, you only need to click the control buttons (zoom/fullscreen/bulk edit) once. It was the fact that two were being opened that blocked the app, because the map reference on the first one was incorrectly destroyed by the plugin, but I'll fix both of these.

**Comment by eltosti** [comment]
Thanks! , yeah, I did it without realizing it
